version: "3"
services:
  backend:
    restart: always
    container_name: "backend"
    working_dir: "/opt/backend/app"
    ports:
      - "8080:8000"
    build:
      context: .
      dockerfile: ./dev/backend/dockerfile
    tty: true
    volumes:
      - ./dev/backend/app:/opt/backend/app
  frontend:
    restart: always
    container_name: "frontend"
    ports:
      - "3000:3000"
    build:
      context: .
      dockerfile: ./dev/frontend/dockerfile
    tty: true
    volumes:
      - ./dev/frontend:/app/frontend
      - /app/frontend/node_modules