# ベースイメージとしてNode.jsを使用
FROM node:22-slim

# 作業ディレクトリを設定
WORKDIR /app/frontend

# パッケージファイルをコピー
COPY ./dev/frontend/package.json ./dev/frontend/package-lock.json ./

# 依存関係をインストール
RUN npm install

# ソースのコピー
COPY ./dev/frontend ./

# 開発用サーバの（ビルドに変更）
CMD ["npm", "run", "dev"]


####################################
######## ビルドに変更 ###############
####################################
